name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
#    A workaround to resolve nuget-issue: https://github.com/dotnet/installer/issues/10171
    - name: NuGet - Add nuget.org (WORKAROUND)
      run: dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
